export type PublicGameProvider = {
  id: string;
  name: string;
  slug: string;
  category: string;
  provider: string;
  imageUrl: string;
  thumbnailUrl: string;
  fallback: string;
  isActive: boolean;
  sortOrder: number;
};

export type PublicProviderGame = {
  id: string;
  title: string;
  name: string;
  slug: string;
  category: string;
  provider: string;
  providerSlug: string;
  imageUrl: string;
  thumbnailUrl: string;
  playUrl: string;
  desktopUrl: string;
  mobileUrl: string;
  isActive: boolean;
  sortOrder: number;
};

export const publicGameProviders = [
  {
    "id": "provider-pragmatic-play",
    "name": "Pragmatic Play",
    "slug": "pragmatic-play",
    "category": "Slots",
    "provider": "PRAGMATIC PLAY",
    "imageUrl": "/providers-grid/gg1.webp",
    "thumbnailUrl": "/providers-grid/gg1.webp",
    "fallback": "PP",
    "isActive": true,
    "sortOrder": 1
  },
  {
    "id": "provider-pg-soft",
    "name": "PG Soft",
    "slug": "pg-soft",
    "category": "Slots",
    "provider": "PG SOFT",
    "imageUrl": "/providers-grid/gg2.webp",
    "thumbnailUrl": "/providers-grid/gg2.webp",
    "fallback": "PG",
    "isActive": true,
    "sortOrder": 2
  },
  {
    "id": "provider-hacksaw-gaming",
    "name": "Hacksaw Gaming",
    "slug": "hacksaw-gaming",
    "category": "Slots",
    "provider": "HACKSAW GAMING",
    "imageUrl": "/providers-grid/gg3.webp",
    "thumbnailUrl": "/providers-grid/gg3.webp",
    "fallback": "HG",
    "isActive": true,
    "sortOrder": 3
  },
  {
    "id": "provider-microgaming",
    "name": "Microgaming",
    "slug": "microgaming",
    "category": "Slots",
    "provider": "MICROGAMING",
    "imageUrl": "/providers-grid/gg4.webp",
    "thumbnailUrl": "/providers-grid/gg4.webp",
    "fallback": "MG",
    "isActive": true,
    "sortOrder": 4
  }
] satisfies PublicGameProvider[];

export const publicProviderGames = {
  "pragmatic-play": [
    {
      "id": "pragmatic-play-gates-of-olympus-1000",
      "title": "Gates of Olympus 1000",
      "name": "Gates of Olympus 1000",
      "slug": "gates-of-olympus-1000",
      "category": "Slots",
      "provider": "PRAGMATIC PLAY",
      "providerSlug": "pragmatic-play",
      "imageUrl": "https://pixel.gambar-lp.com/game-demo/pragmaticplay/GatesofOlympus1000.jpg",
      "thumbnailUrl": "https://pixel.gambar-lp.com/game-demo/pragmaticplay/GatesofOlympus1000.jpg",
      "playUrl": "https://nagaimam.xyz/pragmaticplay/gatesofolympus1000",
      "desktopUrl": "https://nagaimam.xyz/pragmaticplay/gatesofolympus1000",
      "mobileUrl": "https://nagaimam.xyz/pragmaticplay/gatesofolympus1000",
      "isActive": true,
      "sortOrder": 1
    },
    {
      "id": "pragmatic-play-gates-of-gatot-kaca-super-scatter",
      "title": "Gates Of Gatot Kaca Super Scatter",
      "name": "Gates Of Gatot Kaca Super Scatter",
      "slug": "gates-of-gatot-kaca-super-scatter",
      "category": "Slots",
      "provider": "PRAGMATIC PLAY",
      "providerSlug": "pragmatic-play",
      "imageUrl": "https://pixel.gambar-lp.com/game-demo/pragmaticplay/GatesofGatotKacaSuperScatter.webp",
      "thumbnailUrl": "https://pixel.gambar-lp.com/game-demo/pragmaticplay/GatesofGatotKacaSuperScatter.webp",
      "playUrl": "https://nagaimam.xyz/pragmaticplay/gatesofgatotkacasuperscatter",
      "desktopUrl": "https://nagaimam.xyz/pragmaticplay/gatesofgatotkacasuperscatter",
      "mobileUrl": "https://nagaimam.xyz/pragmaticplay/gatesofgatotkacasuperscatter",
      "isActive": true,
      "sortOrder": 2
    },
    {
      "id": "pragmatic-play-starlight-princess-super-scatter",
      "title": "Starlight Princess Super Scatter",
      "name": "Starlight Princess Super Scatter",
      "slug": "starlight-princess-super-scatter",
      "category": "Slots",
      "provider": "PRAGMATIC PLAY",
      "providerSlug": "pragmatic-play",
      "imageUrl": "https://pixel.gambar-lp.com/game-demo/pragmaticplay/StarlightPrincessSuperScatter.webp",
      "thumbnailUrl": "https://pixel.gambar-lp.com/game-demo/pragmaticplay/StarlightPrincessSuperScatter.webp",
      "playUrl": "https://nagaimam.xyz/pragmaticplay/starlightprincesssuperscatter",
      "desktopUrl": "https://nagaimam.xyz/pragmaticplay/starlightprincesssuperscatter",
      "mobileUrl": "https://nagaimam.xyz/pragmaticplay/starlightprincesssuperscatter",
      "isActive": true,
      "sortOrder": 3
    },
    {
      "id": "pragmatic-play-gates-of-olympus-super-scatter",
      "title": "Gates Of Olympus Super Scatter",
      "name": "Gates Of Olympus Super Scatter",
      "slug": "gates-of-olympus-super-scatter",
      "category": "Slots",
      "provider": "PRAGMATIC PLAY",
      "providerSlug": "pragmatic-play",
      "imageUrl": "https://pixel.gambar-lp.com/game-demo/pragmaticplay/vs20olympgold.png",
      "thumbnailUrl": "https://pixel.gambar-lp.com/game-demo/pragmaticplay/vs20olympgold.png",
      "playUrl": "https://nagaimam.xyz/pragmaticplay/gatesofolympussuperscatter",
      "desktopUrl": "https://nagaimam.xyz/pragmaticplay/gatesofolympussuperscatter",
      "mobileUrl": "https://nagaimam.xyz/pragmaticplay/gatesofolympussuperscatter",
      "isActive": true,
      "sortOrder": 4
    },
    {
      "id": "pragmatic-play-sweet-bonanza-super-scatter",
      "title": "Sweet Bonanza Super Scatter",
      "name": "Sweet Bonanza Super Scatter",
      "slug": "sweet-bonanza-super-scatter",
      "category": "Slots",
      "provider": "PRAGMATIC PLAY",
      "providerSlug": "pragmatic-play",
      "imageUrl": "https://pixel.gambar-lp.com/game-demo/pragmaticplay/SweetBonanzaSuperScatter.webp",
      "thumbnailUrl": "https://pixel.gambar-lp.com/game-demo/pragmaticplay/SweetBonanzaSuperScatter.webp",
      "playUrl": "https://nagaimam.xyz/pragmaticplay/sweetbonanzasuperscatter",
      "desktopUrl": "https://nagaimam.xyz/pragmaticplay/sweetbonanzasuperscatter",
      "mobileUrl": "https://nagaimam.xyz/pragmaticplay/sweetbonanzasuperscatter",
      "isActive": true,
      "sortOrder": 5
    },
    {
      "id": "pragmatic-play-kadita-ocean-fury",
      "title": "Kadita Ocean Fury",
      "name": "Kadita Ocean Fury",
      "slug": "kadita-ocean-fury",
      "category": "Slots",
      "provider": "PRAGMATIC PLAY",
      "providerSlug": "pragmatic-play",
      "imageUrl": "https://pixel.gambar-lp.com/game-demo/pragmaticplay/Kadita%20Ocean%20Fury.webp",
      "thumbnailUrl": "https://pixel.gambar-lp.com/game-demo/pragmaticplay/Kadita%20Ocean%20Fury.webp",
      "playUrl": "https://nagaimam.xyz/pragmaticplay/kaditaoceanfury",
      "desktopUrl": "https://nagaimam.xyz/pragmaticplay/kaditaoceanfury",
      "mobileUrl": "https://nagaimam.xyz/pragmaticplay/kaditaoceanfury",
      "isActive": true,
      "sortOrder": 6
    },
    {
      "id": "pragmatic-play-rolling-in-treasures",
      "title": "Rolling In Treasures",
      "name": "Rolling In Treasures",
      "slug": "rolling-in-treasures",
      "category": "Slots",
      "provider": "PRAGMATIC PLAY",
      "providerSlug": "pragmatic-play",
      "imageUrl": "https://pixel.gambar-lp.com/game-demo/pragmaticplay/RollinginTreasures.webp",
      "thumbnailUrl": "https://pixel.gambar-lp.com/game-demo/pragmaticplay/RollinginTreasures.webp",
      "playUrl": "https://nagaimam.xyz/pragmaticplay/rollingintreasures",
      "desktopUrl": "https://nagaimam.xyz/pragmaticplay/rollingintreasures",
      "mobileUrl": "https://nagaimam.xyz/pragmaticplay/rollingintreasures",
      "isActive": true,
      "sortOrder": 7
    },
    {
      "id": "pragmatic-play-cult",
      "title": "CULT.",
      "name": "CULT.",
      "slug": "cult",
      "category": "Slots",
      "provider": "PRAGMATIC PLAY",
      "providerSlug": "pragmatic-play",
      "imageUrl": "https://pixel.gambar-lp.com/game-demo/pragmaticplay/CULT.webp",
      "thumbnailUrl": "https://pixel.gambar-lp.com/game-demo/pragmaticplay/CULT.webp",
      "playUrl": "https://nagaimam.xyz/pragmaticplay/cult.",
      "desktopUrl": "https://nagaimam.xyz/pragmaticplay/cult.",
      "mobileUrl": "https://nagaimam.xyz/pragmaticplay/cult.",
      "isActive": true,
      "sortOrder": 8
    },
    {
      "id": "pragmatic-play-sugar-rush-super-scatter",
      "title": "Sugar Rush Super Scatter",
      "name": "Sugar Rush Super Scatter",
      "slug": "sugar-rush-super-scatter",
      "category": "Slots",
      "provider": "PRAGMATIC PLAY",
      "providerSlug": "pragmatic-play",
      "imageUrl": "https://pixel.gambar-lp.com/game-demo/pragmaticplay/SugarRushSuperScatter.webp",
      "thumbnailUrl": "https://pixel.gambar-lp.com/game-demo/pragmaticplay/SugarRushSuperScatter.webp",
      "playUrl": "https://nagaimam.xyz/pragmaticplay/sugarrushsuperscatter",
      "desktopUrl": "https://nagaimam.xyz/pragmaticplay/sugarrushsuperscatter",
      "mobileUrl": "https://nagaimam.xyz/pragmaticplay/sugarrushsuperscatter",
      "isActive": true,
      "sortOrder": 9
    },
    {
      "id": "pragmatic-play-fortune-of-olympus",
      "title": "Fortune Of Olympus",
      "name": "Fortune Of Olympus",
      "slug": "fortune-of-olympus",
      "category": "Slots",
      "provider": "PRAGMATIC PLAY",
      "providerSlug": "pragmatic-play",
      "imageUrl": "https://pixel.gambar-lp.com/game-demo/pragmaticplay/FortuneofOlympus.webp",
      "thumbnailUrl": "https://pixel.gambar-lp.com/game-demo/pragmaticplay/FortuneofOlympus.webp",
      "playUrl": "https://nagaimam.xyz/pragmaticplay/fortuneofolympus",
      "desktopUrl": "https://nagaimam.xyz/pragmaticplay/fortuneofolympus",
      "mobileUrl": "https://nagaimam.xyz/pragmaticplay/fortuneofolympus",
      "isActive": true,
      "sortOrder": 10
    },
    {
      "id": "pragmatic-play-king-of-spear",
      "title": "King Of Spear",
      "name": "King Of Spear",
      "slug": "king-of-spear",
      "category": "Slots",
      "provider": "PRAGMATIC PLAY",
      "providerSlug": "pragmatic-play",
      "imageUrl": "https://pixel.gambar-lp.com/game-demo/pragmaticplay/KingofSpear.webp",
      "thumbnailUrl": "https://pixel.gambar-lp.com/game-demo/pragmaticplay/KingofSpear.webp",
      "playUrl": "https://nagaimam.xyz/pragmaticplay/kingofspear",
      "desktopUrl": "https://nagaimam.xyz/pragmaticplay/kingofspear",
      "mobileUrl": "https://nagaimam.xyz/pragmaticplay/kingofspear",
      "isActive": true,
      "sortOrder": 11
    },
    {
      "id": "pragmatic-play-gates-of-pyroth",
      "title": "Gates Of Pyroth",
      "name": "Gates Of Pyroth",
      "slug": "gates-of-pyroth",
      "category": "Slots",
      "provider": "PRAGMATIC PLAY",
      "providerSlug": "pragmatic-play",
      "imageUrl": "https://pixel.gambar-lp.com/game-demo/pragmaticplay/GatesofPyroth.webp",
      "thumbnailUrl": "https://pixel.gambar-lp.com/game-demo/pragmaticplay/GatesofPyroth.webp",
      "playUrl": "https://nagaimam.xyz/pragmaticplay/gatesofpyroth",
      "desktopUrl": "https://nagaimam.xyz/pragmaticplay/gatesofpyroth",
      "mobileUrl": "https://nagaimam.xyz/pragmaticplay/gatesofpyroth",
      "isActive": true,
      "sortOrder": 12
    },
    {
      "id": "pragmatic-play-starlight-archer-1000",
      "title": "Starlight Archer 1000",
      "name": "Starlight Archer 1000",
      "slug": "starlight-archer-1000",
      "category": "Slots",
      "provider": "PRAGMATIC PLAY",
      "providerSlug": "pragmatic-play",
      "imageUrl": "https://pixel.gambar-lp.com/game-demo/pragmaticplay/StarlightArcher1000.webp",
      "thumbnailUrl": "https://pixel.gambar-lp.com/game-demo/pragmaticplay/StarlightArcher1000.webp",
      "playUrl": "https://nagaimam.xyz/pragmaticplay/starlightarcher1000",
      "desktopUrl": "https://nagaimam.xyz/pragmaticplay/starlightarcher1000",
      "mobileUrl": "https://nagaimam.xyz/pragmaticplay/starlightarcher1000",
      "isActive": true,
      "sortOrder": 13
    },
    {
      "id": "pragmatic-play-wisdom-of-athena-1000-xmas",
      "title": "Wisdom Of Athena 1000 Xmas",
      "name": "Wisdom Of Athena 1000 Xmas",
      "slug": "wisdom-of-athena-1000-xmas",
      "category": "Slots",
      "provider": "PRAGMATIC PLAY",
      "providerSlug": "pragmatic-play",
      "imageUrl": "https://pixel.gambar-lp.com/game-demo/pragmaticplay/WisdomofAthena1000Xmas.webp",
      "thumbnailUrl": "https://pixel.gambar-lp.com/game-demo/pragmaticplay/WisdomofAthena1000Xmas.webp",
      "playUrl": "https://nagaimam.xyz/pragmaticplay/wisdomofathena1000xmas",
      "desktopUrl": "https://nagaimam.xyz/pragmaticplay/wisdomofathena1000xmas",
      "mobileUrl": "https://nagaimam.xyz/pragmaticplay/wisdomofathena1000xmas",
      "isActive": true,
      "sortOrder": 14
    },
    {
      "id": "pragmatic-play-sweet-craze",
      "title": "Sweet Craze",
      "name": "Sweet Craze",
      "slug": "sweet-craze",
      "category": "Slots",
      "provider": "PRAGMATIC PLAY",
      "providerSlug": "pragmatic-play",
      "imageUrl": "https://pixel.gambar-lp.com/game-demo/pragmaticplay/SweetCraze.webp",
      "thumbnailUrl": "https://pixel.gambar-lp.com/game-demo/pragmaticplay/SweetCraze.webp",
      "playUrl": "https://nagaimam.xyz/pragmaticplay/sweetcraze",
      "desktopUrl": "https://nagaimam.xyz/pragmaticplay/sweetcraze",
      "mobileUrl": "https://nagaimam.xyz/pragmaticplay/sweetcraze",
      "isActive": true,
      "sortOrder": 15
    },
    {
      "id": "pragmatic-play-zeus-vs-typhon",
      "title": "Zeus vs Typhon",
      "name": "Zeus vs Typhon",
      "slug": "zeus-vs-typhon",
      "category": "Slots",
      "provider": "PRAGMATIC PLAY",
      "providerSlug": "pragmatic-play",
      "imageUrl": "https://pixel.gambar-lp.com/game-demo/pragmaticplay/ZeusvsTyphon.webp",
      "thumbnailUrl": "https://pixel.gambar-lp.com/game-demo/pragmaticplay/ZeusvsTyphon.webp",
      "playUrl": "https://nagaimam.xyz/pragmaticplay/zeusvstyphon",
      "desktopUrl": "https://nagaimam.xyz/pragmaticplay/zeusvstyphon",
      "mobileUrl": "https://nagaimam.xyz/pragmaticplay/zeusvstyphon",
      "isActive": true,
      "sortOrder": 16
    },
    {
      "id": "pragmatic-play-spaceman",
      "title": "Spaceman",
      "name": "Spaceman",
      "slug": "spaceman",
      "category": "Slots",
      "provider": "PRAGMATIC PLAY",
      "providerSlug": "pragmatic-play",
      "imageUrl": "https://pixel.gambar-lp.com/game-demo/pragmaticplay/spaceman.jpg",
      "thumbnailUrl": "https://pixel.gambar-lp.com/game-demo/pragmaticplay/spaceman.jpg",
      "playUrl": "https://nagaimam.xyz/pragmaticplay/spaceman",
      "desktopUrl": "https://nagaimam.xyz/pragmaticplay/spaceman",
      "mobileUrl": "https://nagaimam.xyz/pragmaticplay/spaceman",
      "isActive": true,
      "sortOrder": 17
    },
    {
      "id": "pragmatic-play-mahjong-wins-3-black-scatter",
      "title": "Mahjong Wins 3 - Black Scatter",
      "name": "Mahjong Wins 3 - Black Scatter",
      "slug": "mahjong-wins-3-black-scatter",
      "category": "Slots",
      "provider": "PRAGMATIC PLAY",
      "providerSlug": "pragmatic-play",
      "imageUrl": "https://pixel.gambar-lp.com/game-demo/pragmaticplay/MahjongWins3BlackScatter.jpg",
      "thumbnailUrl": "https://pixel.gambar-lp.com/game-demo/pragmaticplay/MahjongWins3BlackScatter.jpg",
      "playUrl": "https://nagaimam.xyz/pragmaticplay/mahjongwins3blackscatter",
      "desktopUrl": "https://nagaimam.xyz/pragmaticplay/mahjongwins3blackscatter",
      "mobileUrl": "https://nagaimam.xyz/pragmaticplay/mahjongwins3blackscatter",
      "isActive": true,
      "sortOrder": 18
    },
    {
      "id": "pragmatic-play-plinko",
      "title": "Plinko+",
      "name": "Plinko+",
      "slug": "plinko",
      "category": "Slots",
      "provider": "PRAGMATIC PLAY",
      "providerSlug": "pragmatic-play",
      "imageUrl": "https://pixel.gambar-lp.com/game-demo/pragmaticplay/ar10plinko.png",
      "thumbnailUrl": "https://pixel.gambar-lp.com/game-demo/pragmaticplay/ar10plinko.png",
      "playUrl": "https://nagaimam.xyz/pragmaticplay/plinko",
      "desktopUrl": "https://nagaimam.xyz/pragmaticplay/plinko",
      "mobileUrl": "https://nagaimam.xyz/pragmaticplay/plinko",
      "isActive": true,
      "sortOrder": 19
    },
    {
      "id": "pragmatic-play-sweet-bonanza-1000",
      "title": "Sweet Bonanza 1000",
      "name": "Sweet Bonanza 1000",
      "slug": "sweet-bonanza-1000",
      "category": "Slots",
      "provider": "PRAGMATIC PLAY",
      "providerSlug": "pragmatic-play",
      "imageUrl": "https://pixel.gambar-lp.com/game-demo/pragmaticplay/vs20fruitswx.png",
      "thumbnailUrl": "https://pixel.gambar-lp.com/game-demo/pragmaticplay/vs20fruitswx.png",
      "playUrl": "https://nagaimam.xyz/pragmaticplay/sweetbonanza1000",
      "desktopUrl": "https://nagaimam.xyz/pragmaticplay/sweetbonanza1000",
      "mobileUrl": "https://nagaimam.xyz/pragmaticplay/sweetbonanza1000",
      "isActive": true,
      "sortOrder": 20
    },
    {
      "id": "pragmatic-play-gates-of-olympus",
      "title": "Gates Of Olympus",
      "name": "Gates Of Olympus",
      "slug": "gates-of-olympus",
      "category": "Slots",
      "provider": "PRAGMATIC PLAY",
      "providerSlug": "pragmatic-play",
      "imageUrl": "https://pixel.gambar-lp.com/game-demo/pragmaticplay/vs20olympgate.png",
      "thumbnailUrl": "https://pixel.gambar-lp.com/game-demo/pragmaticplay/vs20olympgate.png",
      "playUrl": "https://nagaimam.xyz/pragmaticplay/gatesofolympus",
      "desktopUrl": "https://nagaimam.xyz/pragmaticplay/gatesofolympus",
      "mobileUrl": "https://nagaimam.xyz/pragmaticplay/gatesofolympus",
      "isActive": true,
      "sortOrder": 21
    },
    {
      "id": "pragmatic-play-sweet-bonanza-xmas",
      "title": "Sweet Bonanza Xmas",
      "name": "Sweet Bonanza Xmas",
      "slug": "sweet-bonanza-xmas",
      "category": "Slots",
      "provider": "PRAGMATIC PLAY",
      "providerSlug": "pragmatic-play",
      "imageUrl": "https://pixel.gambar-lp.com/game-demo/pragmaticplay/vs20sbxmas.png",
      "thumbnailUrl": "https://pixel.gambar-lp.com/game-demo/pragmaticplay/vs20sbxmas.png",
      "playUrl": "https://nagaimam.xyz/pragmaticplay/sweetbonanzaxmas",
      "desktopUrl": "https://nagaimam.xyz/pragmaticplay/sweetbonanzaxmas",
      "mobileUrl": "https://nagaimam.xyz/pragmaticplay/sweetbonanzaxmas",
      "isActive": true,
      "sortOrder": 22
    },
    {
      "id": "pragmatic-play-sugar-rush",
      "title": "Sugar Rush",
      "name": "Sugar Rush",
      "slug": "sugar-rush",
      "category": "Slots",
      "provider": "PRAGMATIC PLAY",
      "providerSlug": "pragmatic-play",
      "imageUrl": "https://pixel.gambar-lp.com/game-demo/pragmaticplay/SugarRush.jpg",
      "thumbnailUrl": "https://pixel.gambar-lp.com/game-demo/pragmaticplay/SugarRush.jpg",
      "playUrl": "https://nagaimam.xyz/pragmaticplay/sugarrush",
      "desktopUrl": "https://nagaimam.xyz/pragmaticplay/sugarrush",
      "mobileUrl": "https://nagaimam.xyz/pragmaticplay/sugarrush",
      "isActive": true,
      "sortOrder": 23
    },
    {
      "id": "pragmatic-play-wild-west-gold",
      "title": "Wild West Gold",
      "name": "Wild West Gold",
      "slug": "wild-west-gold",
      "category": "Slots",
      "provider": "PRAGMATIC PLAY",
      "providerSlug": "pragmatic-play",
      "imageUrl": "https://pixel.gambar-lp.com/game-demo/pragmaticplay/vs40wildwest.png",
      "thumbnailUrl": "https://pixel.gambar-lp.com/game-demo/pragmaticplay/vs40wildwest.png",
      "playUrl": "https://nagaimam.xyz/pragmaticplay/wildwestgold",
      "desktopUrl": "https://nagaimam.xyz/pragmaticplay/wildwestgold",
      "mobileUrl": "https://nagaimam.xyz/pragmaticplay/wildwestgold",
      "isActive": true,
      "sortOrder": 24
    },
    {
      "id": "pragmatic-play-gates-of-gatot-kaca-1000",
      "title": "Gates of Gatot Kaca 1000",
      "name": "Gates of Gatot Kaca 1000",
      "slug": "gates-of-gatot-kaca-1000",
      "category": "Slots",
      "provider": "PRAGMATIC PLAY",
      "providerSlug": "pragmatic-play",
      "imageUrl": "https://pixel.gambar-lp.com/game-demo/pragmaticplay/vs20gatotx.png",
      "thumbnailUrl": "https://pixel.gambar-lp.com/game-demo/pragmaticplay/vs20gatotx.png",
      "playUrl": "https://nagaimam.xyz/pragmaticplay/gatesofgatotkaca1000",
      "desktopUrl": "https://nagaimam.xyz/pragmaticplay/gatesofgatotkaca1000",
      "mobileUrl": "https://nagaimam.xyz/pragmaticplay/gatesofgatotkaca1000",
      "isActive": true,
      "sortOrder": 25
    },
    {
      "id": "pragmatic-play-sugar-rush-1000",
      "title": "Sugar Rush 1000",
      "name": "Sugar Rush 1000",
      "slug": "sugar-rush-1000",
      "category": "Slots",
      "provider": "PRAGMATIC PLAY",
      "providerSlug": "pragmatic-play",
      "imageUrl": "https://pixel.gambar-lp.com/game-demo/pragmaticplay/vs20sugarrushx.png",
      "thumbnailUrl": "https://pixel.gambar-lp.com/game-demo/pragmaticplay/vs20sugarrushx.png",
      "playUrl": "https://nagaimam.xyz/pragmaticplay/sugarrush1000",
      "desktopUrl": "https://nagaimam.xyz/pragmaticplay/sugarrush1000",
      "mobileUrl": "https://nagaimam.xyz/pragmaticplay/sugarrush1000",
      "isActive": true,
      "sortOrder": 26
    },
    {
      "id": "pragmatic-play-gates-of-olympus-xmas-1000",
      "title": "Gates of Olympus Xmas 1000",
      "name": "Gates of Olympus Xmas 1000",
      "slug": "gates-of-olympus-xmas-1000",
      "category": "Slots",
      "provider": "PRAGMATIC PLAY",
      "providerSlug": "pragmatic-play",
      "imageUrl": "https://pixel.gambar-lp.com/game-demo/pragmaticplay/vs20olympxmas.png",
      "thumbnailUrl": "https://pixel.gambar-lp.com/game-demo/pragmaticplay/vs20olympxmas.png",
      "playUrl": "https://nagaimam.xyz/pragmaticplay/gatesofolympusxmas1000",
      "desktopUrl": "https://nagaimam.xyz/pragmaticplay/gatesofolympusxmas1000",
      "mobileUrl": "https://nagaimam.xyz/pragmaticplay/gatesofolympusxmas1000",
      "isActive": true,
      "sortOrder": 27
    },
    {
      "id": "pragmatic-play-mahjong-wins-gong-xi-fa-cai",
      "title": "Mahjong Wins Gong Xi Fa Cai",
      "name": "Mahjong Wins Gong Xi Fa Cai",
      "slug": "mahjong-wins-gong-xi-fa-cai",
      "category": "Slots",
      "provider": "PRAGMATIC PLAY",
      "providerSlug": "pragmatic-play",
      "imageUrl": "https://pixel.gambar-lp.com/game-demo/pragmaticplay/vswaysmahwgong.png",
      "thumbnailUrl": "https://pixel.gambar-lp.com/game-demo/pragmaticplay/vswaysmahwgong.png",
      "playUrl": "https://nagaimam.xyz/pragmaticplay/mahjongwinsgongxifacai",
      "desktopUrl": "https://nagaimam.xyz/pragmaticplay/mahjongwinsgongxifacai",
      "mobileUrl": "https://nagaimam.xyz/pragmaticplay/mahjongwinsgongxifacai",
      "isActive": true,
      "sortOrder": 28
    },
    {
      "id": "pragmatic-play-starlight-princess",
      "title": "Starlight Princess",
      "name": "Starlight Princess",
      "slug": "starlight-princess",
      "category": "Slots",
      "provider": "PRAGMATIC PLAY",
      "providerSlug": "pragmatic-play",
      "imageUrl": "https://pixel.gambar-lp.com/game-demo/pragmaticplay/Starlight-Princess.jpg",
      "thumbnailUrl": "https://pixel.gambar-lp.com/game-demo/pragmaticplay/Starlight-Princess.jpg",
      "playUrl": "https://nagaimam.xyz/pragmaticplay/starlightprincess",
      "desktopUrl": "https://nagaimam.xyz/pragmaticplay/starlightprincess",
      "mobileUrl": "https://nagaimam.xyz/pragmaticplay/starlightprincess",
      "isActive": true,
      "sortOrder": 29
    },
    {
      "id": "pragmatic-play-starlight-princess-1000",
      "title": "Starlight Princess 1000",
      "name": "Starlight Princess 1000",
      "slug": "starlight-princess-1000",
      "category": "Slots",
      "provider": "PRAGMATIC PLAY",
      "providerSlug": "pragmatic-play",
      "imageUrl": "https://pixel.gambar-lp.com/game-demo/pragmaticplay/StarlightPrincess1000.jpg",
      "thumbnailUrl": "https://pixel.gambar-lp.com/game-demo/pragmaticplay/StarlightPrincess1000.jpg",
      "playUrl": "https://nagaimam.xyz/pragmaticplay/starlightprincess1000",
      "desktopUrl": "https://nagaimam.xyz/pragmaticplay/starlightprincess1000",
      "mobileUrl": "https://nagaimam.xyz/pragmaticplay/starlightprincess1000",
      "isActive": true,
      "sortOrder": 30
    }
  ],
  "pg-soft": [
    {
      "id": "pg-soft-mahjong-ways",
      "title": "Mahjong Ways",
      "name": "Mahjong Ways",
      "slug": "mahjong-ways",
      "category": "Slots",
      "provider": "PG SOFT",
      "providerSlug": "pg-soft",
      "imageUrl": "https://pixel.gambar-lp.com/game-demo/pgsoft/MahjongWays.jpg",
      "thumbnailUrl": "https://pixel.gambar-lp.com/game-demo/pgsoft/MahjongWays.jpg",
      "playUrl": "https://nagaimam.xyz/pgsoft/mahjongways",
      "desktopUrl": "https://nagaimam.xyz/pgsoft/mahjongways",
      "mobileUrl": "https://nagaimam.xyz/pgsoft/mahjongways",
      "isActive": true,
      "sortOrder": 1
    },
    {
      "id": "pg-soft-mahjong-ways-2",
      "title": "Mahjong Ways 2",
      "name": "Mahjong Ways 2",
      "slug": "mahjong-ways-2",
      "category": "Slots",
      "provider": "PG SOFT",
      "providerSlug": "pg-soft",
      "imageUrl": "https://pixel.gambar-lp.com/game-demo/pgsoft/MahjongWays2.jpg",
      "thumbnailUrl": "https://pixel.gambar-lp.com/game-demo/pgsoft/MahjongWays2.jpg",
      "playUrl": "https://nagaimam.xyz/pgsoft/mahjongways2",
      "desktopUrl": "https://nagaimam.xyz/pgsoft/mahjongways2",
      "mobileUrl": "https://nagaimam.xyz/pgsoft/mahjongways2",
      "isActive": true,
      "sortOrder": 2
    },
    {
      "id": "pg-soft-wild-bounty-showdown",
      "title": "Wild Bounty Showdown",
      "name": "Wild Bounty Showdown",
      "slug": "wild-bounty-showdown",
      "category": "Slots",
      "provider": "PG SOFT",
      "providerSlug": "pg-soft",
      "imageUrl": "https://pixel.gambar-lp.com/game-demo/pgsoft/WildBountyShowdown.jpg",
      "thumbnailUrl": "https://pixel.gambar-lp.com/game-demo/pgsoft/WildBountyShowdown.jpg",
      "playUrl": "https://nagaimam.xyz/pgsoft/wildbountyshowdown",
      "desktopUrl": "https://nagaimam.xyz/pgsoft/wildbountyshowdown",
      "mobileUrl": "https://nagaimam.xyz/pgsoft/wildbountyshowdown",
      "isActive": true,
      "sortOrder": 3
    },
    {
      "id": "pg-soft-wild-bandito",
      "title": "Wild Bandito",
      "name": "Wild Bandito",
      "slug": "wild-bandito",
      "category": "Slots",
      "provider": "PG SOFT",
      "providerSlug": "pg-soft",
      "imageUrl": "https://pixel.gambar-lp.com/game-demo/pgsoft/WildBandito.jpg",
      "thumbnailUrl": "https://pixel.gambar-lp.com/game-demo/pgsoft/WildBandito.jpg",
      "playUrl": "https://nagaimam.xyz/pgsoft/wildbandito",
      "desktopUrl": "https://nagaimam.xyz/pgsoft/wildbandito",
      "mobileUrl": "https://nagaimam.xyz/pgsoft/wildbandito",
      "isActive": true,
      "sortOrder": 4
    },
    {
      "id": "pg-soft-mythical-guardians",
      "title": "Mythical Guardians",
      "name": "Mythical Guardians",
      "slug": "mythical-guardians",
      "category": "Slots",
      "provider": "PG SOFT",
      "providerSlug": "pg-soft",
      "imageUrl": "https://pixel.gambar-lp.com/game-demo/pgsoft/MythicalGuardians.webp",
      "thumbnailUrl": "https://pixel.gambar-lp.com/game-demo/pgsoft/MythicalGuardians.webp",
      "playUrl": "https://nagaimam.xyz/pgsoft/mythicalguardians",
      "desktopUrl": "https://nagaimam.xyz/pgsoft/mythicalguardians",
      "mobileUrl": "https://nagaimam.xyz/pgsoft/mythicalguardians",
      "isActive": true,
      "sortOrder": 5
    },
    {
      "id": "pg-soft-alibaba-s-cave-of-fortune",
      "title": "Alibaba's Cave Of Fortune",
      "name": "Alibaba's Cave Of Fortune",
      "slug": "alibaba-s-cave-of-fortune",
      "category": "Slots",
      "provider": "PG SOFT",
      "providerSlug": "pg-soft",
      "imageUrl": "https://pixel.gambar-lp.com/game-demo/pgsoft/AlibabasCaveofFortune.webp",
      "thumbnailUrl": "https://pixel.gambar-lp.com/game-demo/pgsoft/AlibabasCaveofFortune.webp",
      "playUrl": "https://nagaimam.xyz/pgsoft/alibabascaveoffortune",
      "desktopUrl": "https://nagaimam.xyz/pgsoft/alibabascaveoffortune",
      "mobileUrl": "https://nagaimam.xyz/pgsoft/alibabascaveoffortune",
      "isActive": true,
      "sortOrder": 6
    },
    {
      "id": "pg-soft-forbidden-alchemy",
      "title": "Forbidden Alchemy",
      "name": "Forbidden Alchemy",
      "slug": "forbidden-alchemy",
      "category": "Slots",
      "provider": "PG SOFT",
      "providerSlug": "pg-soft",
      "imageUrl": "https://pixel.gambar-lp.com/game-demo/pgsoft/ForbiddenAlchemy.webp",
      "thumbnailUrl": "https://pixel.gambar-lp.com/game-demo/pgsoft/ForbiddenAlchemy.webp",
      "playUrl": "https://nagaimam.xyz/pgsoft/forbiddenalchemy",
      "desktopUrl": "https://nagaimam.xyz/pgsoft/forbiddenalchemy",
      "mobileUrl": "https://nagaimam.xyz/pgsoft/forbiddenalchemy",
      "isActive": true,
      "sortOrder": 7
    },
    {
      "id": "pg-soft-pharaoh-royals",
      "title": "Pharaoh Royals",
      "name": "Pharaoh Royals",
      "slug": "pharaoh-royals",
      "category": "Slots",
      "provider": "PG SOFT",
      "providerSlug": "pg-soft",
      "imageUrl": "https://pixel.gambar-lp.com/game-demo/pgsoft/PharaohRoyals.webp",
      "thumbnailUrl": "https://pixel.gambar-lp.com/game-demo/pgsoft/PharaohRoyals.webp",
      "playUrl": "https://nagaimam.xyz/pgsoft/pharaohroyals",
      "desktopUrl": "https://nagaimam.xyz/pgsoft/pharaohroyals",
      "mobileUrl": "https://nagaimam.xyz/pgsoft/pharaohroyals",
      "isActive": true,
      "sortOrder": 8
    },
    {
      "id": "pg-soft-chocolate-deluxe",
      "title": "Chocolate Deluxe",
      "name": "Chocolate Deluxe",
      "slug": "chocolate-deluxe",
      "category": "Slots",
      "provider": "PG SOFT",
      "providerSlug": "pg-soft",
      "imageUrl": "https://pixel.gambar-lp.com/game-demo/pgsoft/ChocolateDeluxe.jpg",
      "thumbnailUrl": "https://pixel.gambar-lp.com/game-demo/pgsoft/ChocolateDeluxe.jpg",
      "playUrl": "https://nagaimam.xyz/pgsoft/chocolatedeluxe",
      "desktopUrl": "https://nagaimam.xyz/pgsoft/chocolatedeluxe",
      "mobileUrl": "https://nagaimam.xyz/pgsoft/chocolatedeluxe",
      "isActive": true,
      "sortOrder": 9
    },
    {
      "id": "pg-soft-mafia-mayhem",
      "title": "Mafia Mayhem",
      "name": "Mafia Mayhem",
      "slug": "mafia-mayhem",
      "category": "Slots",
      "provider": "PG SOFT",
      "providerSlug": "pg-soft",
      "imageUrl": "https://pixel.gambar-lp.com/game-demo/pgsoft/MafiaMayhem.jpg",
      "thumbnailUrl": "https://pixel.gambar-lp.com/game-demo/pgsoft/MafiaMayhem.jpg",
      "playUrl": "https://nagaimam.xyz/pgsoft/mafiamayhem",
      "desktopUrl": "https://nagaimam.xyz/pgsoft/mafiamayhem",
      "mobileUrl": "https://nagaimam.xyz/pgsoft/mafiamayhem",
      "isActive": true,
      "sortOrder": 10
    },
    {
      "id": "pg-soft-lucky-neko",
      "title": "Lucky Neko",
      "name": "Lucky Neko",
      "slug": "lucky-neko",
      "category": "Slots",
      "provider": "PG SOFT",
      "providerSlug": "pg-soft",
      "imageUrl": "https://pixel.gambar-lp.com/game-demo/pgsoft/LuckyNeko.jpg",
      "thumbnailUrl": "https://pixel.gambar-lp.com/game-demo/pgsoft/LuckyNeko.jpg",
      "playUrl": "https://nagaimam.xyz/pgsoft/luckyneko",
      "desktopUrl": "https://nagaimam.xyz/pgsoft/luckyneko",
      "mobileUrl": "https://nagaimam.xyz/pgsoft/luckyneko",
      "isActive": true,
      "sortOrder": 11
    },
    {
      "id": "pg-soft-fortune-tiger",
      "title": "Fortune Tiger",
      "name": "Fortune Tiger",
      "slug": "fortune-tiger",
      "category": "Slots",
      "provider": "PG SOFT",
      "providerSlug": "pg-soft",
      "imageUrl": "https://pixel.gambar-lp.com/game-demo/pgsoft/FortuneTiger.webp",
      "thumbnailUrl": "https://pixel.gambar-lp.com/game-demo/pgsoft/FortuneTiger.webp",
      "playUrl": "https://nagaimam.xyz/pgsoft/fortunetiger",
      "desktopUrl": "https://nagaimam.xyz/pgsoft/fortunetiger",
      "mobileUrl": "https://nagaimam.xyz/pgsoft/fortunetiger",
      "isActive": true,
      "sortOrder": 12
    },
    {
      "id": "pg-soft-fortune-rabbit",
      "title": "Fortune Rabbit",
      "name": "Fortune Rabbit",
      "slug": "fortune-rabbit",
      "category": "Slots",
      "provider": "PG SOFT",
      "providerSlug": "pg-soft",
      "imageUrl": "https://pixel.gambar-lp.com/game-demo/pgsoft/FortuneRabbit.jpg",
      "thumbnailUrl": "https://pixel.gambar-lp.com/game-demo/pgsoft/FortuneRabbit.jpg",
      "playUrl": "https://nagaimam.xyz/pgsoft/fortunerabbit",
      "desktopUrl": "https://nagaimam.xyz/pgsoft/fortunerabbit",
      "mobileUrl": "https://nagaimam.xyz/pgsoft/fortunerabbit",
      "isActive": true,
      "sortOrder": 13
    },
    {
      "id": "pg-soft-mr-treasure-s-fortune",
      "title": "Mr. Treasure's Fortune",
      "name": "Mr. Treasure's Fortune",
      "slug": "mr-treasure-s-fortune",
      "category": "Slots",
      "provider": "PG SOFT",
      "providerSlug": "pg-soft",
      "imageUrl": "https://pixel.gambar-lp.com/game-demo/pgsoft/MrTreasuresFortune.webp",
      "thumbnailUrl": "https://pixel.gambar-lp.com/game-demo/pgsoft/MrTreasuresFortune.webp",
      "playUrl": "https://nagaimam.xyz/pgsoft/mrtreasuresfortune",
      "desktopUrl": "https://nagaimam.xyz/pgsoft/mrtreasuresfortune",
      "mobileUrl": "https://nagaimam.xyz/pgsoft/mrtreasuresfortune",
      "isActive": true,
      "sortOrder": 14
    },
    {
      "id": "pg-soft-cocktail-nights",
      "title": "Cocktail Nights",
      "name": "Cocktail Nights",
      "slug": "cocktail-nights",
      "category": "Slots",
      "provider": "PG SOFT",
      "providerSlug": "pg-soft",
      "imageUrl": "https://pixel.gambar-lp.com/game-demo/pgsoft/CocktailNights.jpg",
      "thumbnailUrl": "https://pixel.gambar-lp.com/game-demo/pgsoft/CocktailNights.jpg",
      "playUrl": "https://nagaimam.xyz/pgsoft/cocktailnights",
      "desktopUrl": "https://nagaimam.xyz/pgsoft/cocktailnights",
      "mobileUrl": "https://nagaimam.xyz/pgsoft/cocktailnights",
      "isActive": true,
      "sortOrder": 15
    },
    {
      "id": "pg-soft-dreams-of-macau",
      "title": "Dreams Of Macau",
      "name": "Dreams Of Macau",
      "slug": "dreams-of-macau",
      "category": "Slots",
      "provider": "PG SOFT",
      "providerSlug": "pg-soft",
      "imageUrl": "https://pixel.gambar-lp.com/game-demo/pgsoft/DreamsOfMacau.jpg",
      "thumbnailUrl": "https://pixel.gambar-lp.com/game-demo/pgsoft/DreamsOfMacau.jpg",
      "playUrl": "https://nagaimam.xyz/pgsoft/dreamsofmacau",
      "desktopUrl": "https://nagaimam.xyz/pgsoft/dreamsofmacau",
      "mobileUrl": "https://nagaimam.xyz/pgsoft/dreamsofmacau",
      "isActive": true,
      "sortOrder": 16
    },
    {
      "id": "pg-soft-majestic-empire",
      "title": "Majestic Empire",
      "name": "Majestic Empire",
      "slug": "majestic-empire",
      "category": "Slots",
      "provider": "PG SOFT",
      "providerSlug": "pg-soft",
      "imageUrl": "https://pixel.gambar-lp.com/game-demo/pgsoft/MajesticEmpire.webp",
      "thumbnailUrl": "https://pixel.gambar-lp.com/game-demo/pgsoft/MajesticEmpire.webp",
      "playUrl": "https://nagaimam.xyz/pgsoft/majesticempire",
      "desktopUrl": "https://nagaimam.xyz/pgsoft/majesticempire",
      "mobileUrl": "https://nagaimam.xyz/pgsoft/majesticempire",
      "isActive": true,
      "sortOrder": 17
    },
    {
      "id": "pg-soft-treasures-of-aztec",
      "title": "Treasures of Aztec",
      "name": "Treasures of Aztec",
      "slug": "treasures-of-aztec",
      "category": "Slots",
      "provider": "PG SOFT",
      "providerSlug": "pg-soft",
      "imageUrl": "https://pixel.gambar-lp.com/game-demo/pgsoft/TreasureOfAztec.jpg",
      "thumbnailUrl": "https://pixel.gambar-lp.com/game-demo/pgsoft/TreasureOfAztec.jpg",
      "playUrl": "https://nagaimam.xyz/pgsoft/treasuresofaztec",
      "desktopUrl": "https://nagaimam.xyz/pgsoft/treasuresofaztec",
      "mobileUrl": "https://nagaimam.xyz/pgsoft/treasuresofaztec",
      "isActive": true,
      "sortOrder": 18
    },
    {
      "id": "pg-soft-the-great-icescape",
      "title": "The Great Icescape",
      "name": "The Great Icescape",
      "slug": "the-great-icescape",
      "category": "Slots",
      "provider": "PG SOFT",
      "providerSlug": "pg-soft",
      "imageUrl": "https://pixel.gambar-lp.com/game-demo/pgsoft/TheGreatIcescape.jpg",
      "thumbnailUrl": "https://pixel.gambar-lp.com/game-demo/pgsoft/TheGreatIcescape.jpg",
      "playUrl": "https://nagaimam.xyz/pgsoft/thegreaticescape",
      "desktopUrl": "https://nagaimam.xyz/pgsoft/thegreaticescape",
      "mobileUrl": "https://nagaimam.xyz/pgsoft/thegreaticescape",
      "isActive": true,
      "sortOrder": 19
    },
    {
      "id": "pg-soft-dragon-hatch",
      "title": "Dragon Hatch",
      "name": "Dragon Hatch",
      "slug": "dragon-hatch",
      "category": "Slots",
      "provider": "PG SOFT",
      "providerSlug": "pg-soft",
      "imageUrl": "https://pixel.gambar-lp.com/game-demo/pgsoft/DragonHatch.jpg",
      "thumbnailUrl": "https://pixel.gambar-lp.com/game-demo/pgsoft/DragonHatch.jpg",
      "playUrl": "https://nagaimam.xyz/pgsoft/dragonhatch",
      "desktopUrl": "https://nagaimam.xyz/pgsoft/dragonhatch",
      "mobileUrl": "https://nagaimam.xyz/pgsoft/dragonhatch",
      "isActive": true,
      "sortOrder": 20
    },
    {
      "id": "pg-soft-caishen-wins",
      "title": "Caishen Wins",
      "name": "Caishen Wins",
      "slug": "caishen-wins",
      "category": "Slots",
      "provider": "PG SOFT",
      "providerSlug": "pg-soft",
      "imageUrl": "https://pixel.gambar-lp.com/game-demo/pgsoft/CaishenWins.jpg",
      "thumbnailUrl": "https://pixel.gambar-lp.com/game-demo/pgsoft/CaishenWins.jpg",
      "playUrl": "https://nagaimam.xyz/pgsoft/caishenwins",
      "desktopUrl": "https://nagaimam.xyz/pgsoft/caishenwins",
      "mobileUrl": "https://nagaimam.xyz/pgsoft/caishenwins",
      "isActive": true,
      "sortOrder": 21
    },
    {
      "id": "pg-soft-speed-winner",
      "title": "Speed Winner",
      "name": "Speed Winner",
      "slug": "speed-winner",
      "category": "Slots",
      "provider": "PG SOFT",
      "providerSlug": "pg-soft",
      "imageUrl": "https://pixel.gambar-lp.com/game-demo/pgsoft/SpeedWinner.jpg",
      "thumbnailUrl": "https://pixel.gambar-lp.com/game-demo/pgsoft/SpeedWinner.jpg",
      "playUrl": "https://nagaimam.xyz/pgsoft/speedwinner",
      "desktopUrl": "https://nagaimam.xyz/pgsoft/speedwinner",
      "mobileUrl": "https://nagaimam.xyz/pgsoft/speedwinner",
      "isActive": true,
      "sortOrder": 22
    },
    {
      "id": "pg-soft-queen-of-bounty",
      "title": "Queen of Bounty",
      "name": "Queen of Bounty",
      "slug": "queen-of-bounty",
      "category": "Slots",
      "provider": "PG SOFT",
      "providerSlug": "pg-soft",
      "imageUrl": "https://pixel.gambar-lp.com/game-demo/pgsoft/QueenOfBounty.jpg",
      "thumbnailUrl": "https://pixel.gambar-lp.com/game-demo/pgsoft/QueenOfBounty.jpg",
      "playUrl": "https://nagaimam.xyz/pgsoft/queenofbounty",
      "desktopUrl": "https://nagaimam.xyz/pgsoft/queenofbounty",
      "mobileUrl": "https://nagaimam.xyz/pgsoft/queenofbounty",
      "isActive": true,
      "sortOrder": 23
    },
    {
      "id": "pg-soft-pinata-wins",
      "title": "Pinata Wins",
      "name": "Pinata Wins",
      "slug": "pinata-wins",
      "category": "Slots",
      "provider": "PG SOFT",
      "providerSlug": "pg-soft",
      "imageUrl": "https://pixel.gambar-lp.com/game-demo/pgsoft/PinataWins.jpg",
      "thumbnailUrl": "https://pixel.gambar-lp.com/game-demo/pgsoft/PinataWins.jpg",
      "playUrl": "https://nagaimam.xyz/pgsoft/pinatawins",
      "desktopUrl": "https://nagaimam.xyz/pgsoft/pinatawins",
      "mobileUrl": "https://nagaimam.xyz/pgsoft/pinatawins",
      "isActive": true,
      "sortOrder": 24
    },
    {
      "id": "pg-soft-fortune-ox",
      "title": "Fortune Ox",
      "name": "Fortune Ox",
      "slug": "fortune-ox",
      "category": "Slots",
      "provider": "PG SOFT",
      "providerSlug": "pg-soft",
      "imageUrl": "https://pixel.gambar-lp.com/game-demo/pgsoft/FortuneOx.jpg",
      "thumbnailUrl": "https://pixel.gambar-lp.com/game-demo/pgsoft/FortuneOx.jpg",
      "playUrl": "https://nagaimam.xyz/pgsoft/fortuneox",
      "desktopUrl": "https://nagaimam.xyz/pgsoft/fortuneox",
      "mobileUrl": "https://nagaimam.xyz/pgsoft/fortuneox",
      "isActive": true,
      "sortOrder": 25
    },
    {
      "id": "pg-soft-wild-ape",
      "title": "Wild Ape",
      "name": "Wild Ape",
      "slug": "wild-ape",
      "category": "Slots",
      "provider": "PG SOFT",
      "providerSlug": "pg-soft",
      "imageUrl": "https://pixel.gambar-lp.com/game-demo/pgsoft/WildApe.jpg",
      "thumbnailUrl": "https://pixel.gambar-lp.com/game-demo/pgsoft/WildApe.jpg",
      "playUrl": "https://nagaimam.xyz/pgsoft/wildape",
      "desktopUrl": "https://nagaimam.xyz/pgsoft/wildape",
      "mobileUrl": "https://nagaimam.xyz/pgsoft/wildape",
      "isActive": true,
      "sortOrder": 26
    },
    {
      "id": "pg-soft-ways-of-the-qilin",
      "title": "Ways of the Qilin",
      "name": "Ways of the Qilin",
      "slug": "ways-of-the-qilin",
      "category": "Slots",
      "provider": "PG SOFT",
      "providerSlug": "pg-soft",
      "imageUrl": "https://pixel.gambar-lp.com/game-demo/pgsoft/WaysOfQilin.jpg",
      "thumbnailUrl": "https://pixel.gambar-lp.com/game-demo/pgsoft/WaysOfQilin.jpg",
      "playUrl": "https://nagaimam.xyz/pgsoft/waysoftheqilin",
      "desktopUrl": "https://nagaimam.xyz/pgsoft/waysoftheqilin",
      "mobileUrl": "https://nagaimam.xyz/pgsoft/waysoftheqilin",
      "isActive": true,
      "sortOrder": 27
    },
    {
      "id": "pg-soft-oishi-delights",
      "title": "Oishi Delights",
      "name": "Oishi Delights",
      "slug": "oishi-delights",
      "category": "Slots",
      "provider": "PG SOFT",
      "providerSlug": "pg-soft",
      "imageUrl": "https://pixel.gambar-lp.com/game-demo/pgsoft/OishiDelights.jpg",
      "thumbnailUrl": "https://pixel.gambar-lp.com/game-demo/pgsoft/OishiDelights.jpg",
      "playUrl": "https://nagaimam.xyz/pgsoft/oishidelights",
      "desktopUrl": "https://nagaimam.xyz/pgsoft/oishidelights",
      "mobileUrl": "https://nagaimam.xyz/pgsoft/oishidelights",
      "isActive": true,
      "sortOrder": 28
    },
    {
      "id": "pg-soft-yakuza-honor",
      "title": "Yakuza Honor",
      "name": "Yakuza Honor",
      "slug": "yakuza-honor",
      "category": "Slots",
      "provider": "PG SOFT",
      "providerSlug": "pg-soft",
      "imageUrl": "https://pixel.gambar-lp.com/game-demo/pgsoft/YakuzaHonor.jpg",
      "thumbnailUrl": "https://pixel.gambar-lp.com/game-demo/pgsoft/YakuzaHonor.jpg",
      "playUrl": "https://nagaimam.xyz/pgsoft/yakuzahonor",
      "desktopUrl": "https://nagaimam.xyz/pgsoft/yakuzahonor",
      "mobileUrl": "https://nagaimam.xyz/pgsoft/yakuzahonor",
      "isActive": true,
      "sortOrder": 29
    },
    {
      "id": "pg-soft-geisha-s-revenge",
      "title": "Geisha's Revenge",
      "name": "Geisha's Revenge",
      "slug": "geisha-s-revenge",
      "category": "Slots",
      "provider": "PG SOFT",
      "providerSlug": "pg-soft",
      "imageUrl": "https://pixel.gambar-lp.com/game-demo/pgsoft/GeishasRevenge.jpg",
      "thumbnailUrl": "https://pixel.gambar-lp.com/game-demo/pgsoft/GeishasRevenge.jpg",
      "playUrl": "https://nagaimam.xyz/pgsoft/geishasrevenge",
      "desktopUrl": "https://nagaimam.xyz/pgsoft/geishasrevenge",
      "mobileUrl": "https://nagaimam.xyz/pgsoft/geishasrevenge",
      "isActive": true,
      "sortOrder": 30
    }
  ],
  "hacksaw-gaming": [
    {
      "id": "hacksaw-gaming-3-cursed-chests",
      "title": "3 Cursed Chests",
      "name": "3 Cursed Chests",
      "slug": "3-cursed-chests",
      "category": "Slots",
      "provider": "HACKSAW GAMING",
      "providerSlug": "hacksaw-gaming",
      "imageUrl": "https://great.com/wp-content/uploads/2026/04/3-Cursed-Chests.jpg",
      "thumbnailUrl": "https://great.com/wp-content/uploads/2026/04/3-Cursed-Chests.jpg",
      "playUrl": "https://static-live.hacksawgaming.com/2296/1.24.0/index.html?language=en&channel=desktop&gameid=2296&mode=2&token=123&partner=demo&env=https://rgs-demo.hacksawgaming.com/api&realmoneyenv=https://rgs-demo.hacksawgaming.com/api&alwaysredirect=true",
      "desktopUrl": "https://static-live.hacksawgaming.com/2296/1.24.0/index.html?language=en&channel=desktop&gameid=2296&mode=2&token=123&partner=demo&env=https://rgs-demo.hacksawgaming.com/api&realmoneyenv=https://rgs-demo.hacksawgaming.com/api&alwaysredirect=true",
      "mobileUrl": "https://static-live.hacksawgaming.com/2296/1.24.0/index.html?language=en&channel=mobile&gameid=2296&mode=2&token=123&partner=demo&env=https://rgs-demo.hacksawgaming.com/api&realmoneyenv=https://rgs-demo.hacksawgaming.com/api&alwaysredirect=true",
      "isActive": true,
      "sortOrder": 1
    },
    {
      "id": "hacksaw-gaming-le-fisherman",
      "title": "Le Fisherman",
      "name": "Le Fisherman",
      "slug": "le-fisherman",
      "category": "Slots",
      "provider": "HACKSAW GAMING",
      "providerSlug": "hacksaw-gaming",
      "imageUrl": "https://great.com/wp-content/uploads/2026/01/le-fisherman-slot-266x354.png",
      "thumbnailUrl": "https://great.com/wp-content/uploads/2026/01/le-fisherman-slot-266x354.png",
      "playUrl": "https://static-live.hacksawgaming.com/launcher/static-launcher.html?gameid=2057&channel=desktop&language=en&partner=hacksaw&mode=demo&token=123",
      "desktopUrl": "https://static-live.hacksawgaming.com/launcher/static-launcher.html?gameid=2057&channel=desktop&language=en&partner=hacksaw&mode=demo&token=123",
      "mobileUrl": "https://static-live.hacksawgaming.com/launcher/static-launcher.html?gameid=2057&channel=mobile&language=en&partner=hacksaw&mode=demo&token=123",
      "isActive": true,
      "sortOrder": 2
    },
    {
      "id": "hacksaw-gaming-rise-of-fortuna",
      "title": "Rise Of Fortuna",
      "name": "Rise Of Fortuna",
      "slug": "rise-of-fortuna",
      "category": "Slots",
      "provider": "HACKSAW GAMING",
      "providerSlug": "hacksaw-gaming",
      "imageUrl": "https://great.com/wp-content/uploads/2026/05/Rise-of-Fortuna.jpg",
      "thumbnailUrl": "https://great.com/wp-content/uploads/2026/05/Rise-of-Fortuna.jpg",
      "playUrl": "https://static-live.hacksawgaming.com/2213/1.19.0/index.html?language=en&channel=desktop&gameid=2213&mode=2&token=123&partner=demo&env=https://rgs-demo.hacksawgaming.com/api&realmoneyenv=https://rgs-demo.hacksawgaming.com/api&alwaysredirect=true",
      "desktopUrl": "https://static-live.hacksawgaming.com/2213/1.19.0/index.html?language=en&channel=desktop&gameid=2213&mode=2&token=123&partner=demo&env=https://rgs-demo.hacksawgaming.com/api&realmoneyenv=https://rgs-demo.hacksawgaming.com/api&alwaysredirect=true",
      "mobileUrl": "https://static-live.hacksawgaming.com/2213/1.19.0/index.html?language=en&channel=mobile&gameid=2213&mode=2&token=123&partner=demo&env=https://rgs-demo.hacksawgaming.com/api&realmoneyenv=https://rgs-demo.hacksawgaming.com/api&alwaysredirect=true",
      "isActive": true,
      "sortOrder": 3
    },
    {
      "id": "hacksaw-gaming-le-bandit",
      "title": "Le Bandit",
      "name": "Le Bandit",
      "slug": "le-bandit",
      "category": "Slots",
      "provider": "HACKSAW GAMING",
      "providerSlug": "hacksaw-gaming",
      "imageUrl": "https://great.com/wp-content/uploads/2024/09/26092024_1727337917-266x354.jpg",
      "thumbnailUrl": "https://great.com/wp-content/uploads/2024/09/26092024_1727337917-266x354.jpg",
      "playUrl": "https://static-stg.hacksawgaming.com/launcher/static-launcher.html?gameid=1309&channel=desktop&language=en&partner=stg&mode=demo&token=123",
      "desktopUrl": "https://static-stg.hacksawgaming.com/launcher/static-launcher.html?gameid=1309&channel=desktop&language=en&partner=stg&mode=demo&token=123",
      "mobileUrl": "https://static-stg.hacksawgaming.com/launcher/static-launcher.html?gameid=1309&channel=mobile&language=en&partner=stg&mode=demo&token=123",
      "isActive": true,
      "sortOrder": 4
    },
    {
      "id": "hacksaw-gaming-red-rascal",
      "title": "Red Rascal",
      "name": "Red Rascal",
      "slug": "red-rascal",
      "category": "Slots",
      "provider": "HACKSAW GAMING",
      "providerSlug": "hacksaw-gaming",
      "imageUrl": "https://great.com/wp-content/uploads/2026/04/Red-Rascal.jpg",
      "thumbnailUrl": "https://great.com/wp-content/uploads/2026/04/Red-Rascal.jpg",
      "playUrl": "https://static-live.hacksawgaming.com/2274/1.20.0/index.html?language=en&channel=desktop&gameid=2274&mode=2&token=123&partner=demo&env=https://rgs-demo.hacksawgaming.com/api&realmoneyenv=https://rgs-demo.hacksawgaming.com/api&alwaysredirect=true",
      "desktopUrl": "https://static-live.hacksawgaming.com/2274/1.20.0/index.html?language=en&channel=desktop&gameid=2274&mode=2&token=123&partner=demo&env=https://rgs-demo.hacksawgaming.com/api&realmoneyenv=https://rgs-demo.hacksawgaming.com/api&alwaysredirect=true",
      "mobileUrl": "https://static-live.hacksawgaming.com/2274/1.20.0/index.html?language=en&channel=mobile&gameid=2274&mode=2&token=123&partner=demo&env=https://rgs-demo.hacksawgaming.com/api&realmoneyenv=https://rgs-demo.hacksawgaming.com/api&alwaysredirect=true",
      "isActive": true,
      "sortOrder": 5
    },
    {
      "id": "hacksaw-gaming-wanted-dead-or-a-wild",
      "title": "Wanted Dead Or A Wild",
      "name": "Wanted Dead Or A Wild",
      "slug": "wanted-dead-or-a-wild",
      "category": "Slots",
      "provider": "HACKSAW GAMING",
      "providerSlug": "hacksaw-gaming",
      "imageUrl": "https://great.com/wp-content/uploads/2024/09/26092024_1727338985-1-266x354.jpeg",
      "thumbnailUrl": "https://great.com/wp-content/uploads/2024/09/26092024_1727338985-1-266x354.jpeg",
      "playUrl": "https://static-stg.hacksawgaming.com/launcher/static-launcher.html?gameid=1067&channel=desktop&language=en&partner=stg&mode=demo&token=123",
      "desktopUrl": "https://static-stg.hacksawgaming.com/launcher/static-launcher.html?gameid=1067&channel=desktop&language=en&partner=stg&mode=demo&token=123",
      "mobileUrl": "https://static-stg.hacksawgaming.com/launcher/static-launcher.html?gameid=1067&channel=mobile&language=en&partner=stg&mode=demo&token=123",
      "isActive": true,
      "sortOrder": 6
    },
    {
      "id": "hacksaw-gaming-epic-bullets-bounty",
      "title": "Epic Bullets & Bounty",
      "name": "Epic Bullets & Bounty",
      "slug": "epic-bullets-bounty",
      "category": "Slots",
      "provider": "HACKSAW GAMING",
      "providerSlug": "hacksaw-gaming",
      "imageUrl": "https://great.com/wp-content/uploads/2026/03/Epic-Bullets-Bounty-266x354.png",
      "thumbnailUrl": "https://great.com/wp-content/uploads/2026/03/Epic-Bullets-Bounty-266x354.png",
      "playUrl": "https://static-live.hacksawgaming.com/2185/1.2.2/index.html?language=en&channel=desktop&gameid=2185&mode=2&token=123&partner=demo&env=https://rgs-demo.hacksawgaming.com/api&realmoneyenv=https://rgs-demo.hacksawgaming.com/api&alwaysredirect=true",
      "desktopUrl": "https://static-live.hacksawgaming.com/2185/1.2.2/index.html?language=en&channel=desktop&gameid=2185&mode=2&token=123&partner=demo&env=https://rgs-demo.hacksawgaming.com/api&realmoneyenv=https://rgs-demo.hacksawgaming.com/api&alwaysredirect=true",
      "mobileUrl": "https://static-live.hacksawgaming.com/2185/1.2.2/index.html?language=en&channel=mobile&gameid=2185&mode=2&token=123&partner=demo&env=https://rgs-demo.hacksawgaming.com/api&realmoneyenv=https://rgs-demo.hacksawgaming.com/api&alwaysredirect=true",
      "isActive": true,
      "sortOrder": 7
    },
    {
      "id": "hacksaw-gaming-le-hooligan",
      "title": "Le Hooligan",
      "name": "Le Hooligan",
      "slug": "le-hooligan",
      "category": "Slots",
      "provider": "HACKSAW GAMING",
      "providerSlug": "hacksaw-gaming",
      "imageUrl": "https://great.com/wp-content/uploads/2026/06/Le-Hooligan_53673_.05062026_1780685951-1-266x354.jpeg",
      "thumbnailUrl": "https://great.com/wp-content/uploads/2026/06/Le-Hooligan_53673_.05062026_1780685951-1-266x354.jpeg",
      "playUrl": "https://static-stg.hacksawgaming.com/2470/1.1.4/index.html?language=en&channel=desktop&gameid=2470&mode=2&token=123&partner=stg&env=https://rgs-hacksaw-fun-stg.hacksawgaming.com/api&realmoneyenv=https://rgs-hacksaw-stg.hacksawgaming.com/api&alwaysredirect=true",
      "desktopUrl": "https://static-stg.hacksawgaming.com/2470/1.1.4/index.html?language=en&channel=desktop&gameid=2470&mode=2&token=123&partner=stg&env=https://rgs-hacksaw-fun-stg.hacksawgaming.com/api&realmoneyenv=https://rgs-hacksaw-stg.hacksawgaming.com/api&alwaysredirect=true",
      "mobileUrl": "https://static-stg.hacksawgaming.com/2470/1.1.4/index.html?language=en&channel=mobile&gameid=2470&mode=2&token=123&partner=stg&env=https://rgs-hacksaw-fun-stg.hacksawgaming.com/api&realmoneyenv=https://rgs-hacksaw-stg.hacksawgaming.com/api&alwaysredirect=true",
      "isActive": true,
      "sortOrder": 8
    },
    {
      "id": "hacksaw-gaming-plinko",
      "title": "Plinko",
      "name": "Plinko",
      "slug": "plinko",
      "category": "Slots",
      "provider": "HACKSAW GAMING",
      "providerSlug": "hacksaw-gaming",
      "imageUrl": "https://great.com/wp-content/uploads/2024/11/Plinko-266x354.png",
      "thumbnailUrl": "https://great.com/wp-content/uploads/2024/11/Plinko-266x354.png",
      "playUrl": "https://static-live.hacksawgaming.com/1294/1.82.0/index.html?language=en&channel=desktop&gameid=1294&mode=2&token=123131&lobbyurl=https%3A%2F%2Fwww.hacksawgaming.com&currency=EUR&partner=demo&env=https://rgs-demo.hacksawgaming.com/api&realmoneyenv=https://rgs-demo.hacksawgaming.com/api",
      "desktopUrl": "https://static-live.hacksawgaming.com/1294/1.82.0/index.html?language=en&channel=desktop&gameid=1294&mode=2&token=123131&lobbyurl=https%3A%2F%2Fwww.hacksawgaming.com&currency=EUR&partner=demo&env=https://rgs-demo.hacksawgaming.com/api&realmoneyenv=https://rgs-demo.hacksawgaming.com/api",
      "mobileUrl": "https://static-live.hacksawgaming.com/1294/1.82.0/index.html?language=en&channel=mobile&gameid=1294&mode=2&token=123131&lobbyurl=https%3A%2F%2Fwww.hacksawgaming.com&currency=EUR&partner=demo&env=https://rgs-demo.hacksawgaming.com/api&realmoneyenv=https://rgs-demo.hacksawgaming.com/api",
      "isActive": true,
      "sortOrder": 9
    },
    {
      "id": "hacksaw-gaming-deal-with-death",
      "title": "Deal With Death",
      "name": "Deal With Death",
      "slug": "deal-with-death",
      "category": "Slots",
      "provider": "HACKSAW GAMING",
      "providerSlug": "hacksaw-gaming",
      "imageUrl": "https://great.com/wp-content/uploads/2026/01/Deal-With-Death.png",
      "thumbnailUrl": "https://great.com/wp-content/uploads/2026/01/Deal-With-Death.png",
      "playUrl": "https://static-live.hacksawgaming.com/2000/1.29.2/index.html?language=en&channel=desktop&gameid=2000&mode=2&token=123&partner=demo&env=https://rgs-demo.hacksawgaming.com/api&realmoneyenv=https://rgs-demo.hacksawgaming.com/api&alwaysredirect=true",
      "desktopUrl": "https://static-live.hacksawgaming.com/2000/1.29.2/index.html?language=en&channel=desktop&gameid=2000&mode=2&token=123&partner=demo&env=https://rgs-demo.hacksawgaming.com/api&realmoneyenv=https://rgs-demo.hacksawgaming.com/api&alwaysredirect=true",
      "mobileUrl": "https://static-live.hacksawgaming.com/2000/1.29.2/index.html?language=en&channel=mobile&gameid=2000&mode=2&token=123&partner=demo&env=https://rgs-demo.hacksawgaming.com/api&realmoneyenv=https://rgs-demo.hacksawgaming.com/api&alwaysredirect=true",
      "isActive": true,
      "sortOrder": 10
    },
    {
      "id": "hacksaw-gaming-duel-at-dawn",
      "title": "Duel At Dawn",
      "name": "Duel At Dawn",
      "slug": "duel-at-dawn",
      "category": "Slots",
      "provider": "HACKSAW GAMING",
      "providerSlug": "hacksaw-gaming",
      "imageUrl": "https://great.com/wp-content/uploads/2024/11/duel_at_dawn-266x354.png",
      "thumbnailUrl": "https://great.com/wp-content/uploads/2024/11/duel_at_dawn-266x354.png",
      "playUrl": "https://static-live.hacksawgaming.com/1620/1.35.2/index.html?language=en&channel=desktop&gameid=1620&mode=2&token=123131&lobbyurl=https%3A%2F%2Fwww.hacksawgaming.com&currency=EUR&partner=demo&env=https://rgs-demo.hacksawgaming.com/api&realmoneyenv=https://rgs-demo.hacksawgaming.com/api",
      "desktopUrl": "https://static-live.hacksawgaming.com/1620/1.35.2/index.html?language=en&channel=desktop&gameid=1620&mode=2&token=123131&lobbyurl=https%3A%2F%2Fwww.hacksawgaming.com&currency=EUR&partner=demo&env=https://rgs-demo.hacksawgaming.com/api&realmoneyenv=https://rgs-demo.hacksawgaming.com/api",
      "mobileUrl": "https://static-live.hacksawgaming.com/1620/1.35.2/index.html?language=en&channel=mobile&gameid=1620&mode=2&token=123131&lobbyurl=https%3A%2F%2Fwww.hacksawgaming.com&currency=EUR&partner=demo&env=https://rgs-demo.hacksawgaming.com/api&realmoneyenv=https://rgs-demo.hacksawgaming.com/api",
      "isActive": true,
      "sortOrder": 11
    },
    {
      "id": "hacksaw-gaming-le-cowboy",
      "title": "Le Cowboy",
      "name": "Le Cowboy",
      "slug": "le-cowboy",
      "category": "Slots",
      "provider": "HACKSAW GAMING",
      "providerSlug": "hacksaw-gaming",
      "imageUrl": "https://great.com/wp-content/uploads/2025/11/Le-Cowboy-266x354.png",
      "thumbnailUrl": "https://great.com/wp-content/uploads/2025/11/Le-Cowboy-266x354.png",
      "playUrl": "https://static-live.hacksawgaming.com/launcher/static-launcher.html?gameid=1924&channel=desktop&language=en&partner=bigwinboard&mode=demo&token=123",
      "desktopUrl": "https://static-live.hacksawgaming.com/launcher/static-launcher.html?gameid=1924&channel=desktop&language=en&partner=bigwinboard&mode=demo&token=123",
      "mobileUrl": "https://static-live.hacksawgaming.com/launcher/static-launcher.html?gameid=1924&channel=mobile&language=en&partner=bigwinboard&mode=demo&token=123",
      "isActive": true,
      "sortOrder": 12
    }
  ],
  "microgaming": [
    {
      "id": "microgaming-luna-princess",
      "title": "Luna Princess",
      "name": "Luna Princess",
      "slug": "luna-princess",
      "category": "Slots",
      "provider": "MICROGAMING",
      "providerSlug": "microgaming",
      "imageUrl": "https://AIiTGNuAPvSpmLDzUi4pD1vmUiALBQqedVRcnQxjtGA.bithe.net/ImageBuilder/v1/images/en/Square/600x600/SMG_lunaPrincessLinkMerge.JPG",
      "thumbnailUrl": "https://AIiTGNuAPvSpmLDzUi4pD1vmUiALBQqedVRcnQxjtGA.bithe.net/ImageBuilder/v1/images/en/Square/600x600/SMG_lunaPrincessLinkMerge.JPG",
      "playUrl": "https://aiitgnuapvspmldzui4pd1vmuialbqqedvrcnqxjtga.goplaylaunch.com/?gameId=SMG_lunaPrincessLinkMerge&languageCode=en&host=desktop",
      "desktopUrl": "https://aiitgnuapvspmldzui4pd1vmuialbqqedvrcnqxjtga.goplaylaunch.com/?gameId=SMG_lunaPrincessLinkMerge&languageCode=en&host=desktop",
      "mobileUrl": "https://aiitgnuapvspmldzui4pd1vmuialbqqedvrcnqxjtga.goplaylaunch.com/?gameId=SMG_lunaPrincessLinkMerge&languageCode=en&host=mobile",
      "isActive": true,
      "sortOrder": 1
    },
    {
      "id": "microgaming-queen-of-cairo-royal-maxways",
      "title": "Queen Of Cairo Royal Maxways",
      "name": "Queen Of Cairo Royal Maxways",
      "slug": "queen-of-cairo-royal-maxways",
      "category": "Slots",
      "provider": "MICROGAMING",
      "providerSlug": "microgaming",
      "imageUrl": "https://AIiTGNuAPvSpmLDzUi4pD1vmUiALBQqedVRcnQxjtGA.bithe.net/ImageBuilder/v1/images/en/Square/600x600/SMG_queenOfCairoRoyalMaxways.JPG",
      "thumbnailUrl": "https://AIiTGNuAPvSpmLDzUi4pD1vmUiALBQqedVRcnQxjtGA.bithe.net/ImageBuilder/v1/images/en/Square/600x600/SMG_queenOfCairoRoyalMaxways.JPG",
      "playUrl": "https://aiitgnuapvspmldzui4pd1vmuialbqqedvrcnqxjtga.goplaylaunch.com/?gameId=SMG_queenOfCairoRoyalMaxways&languageCode=en&host=desktop",
      "desktopUrl": "https://aiitgnuapvspmldzui4pd1vmuialbqqedvrcnqxjtga.goplaylaunch.com/?gameId=SMG_queenOfCairoRoyalMaxways&languageCode=en&host=desktop",
      "mobileUrl": "https://aiitgnuapvspmldzui4pd1vmuialbqqedvrcnqxjtga.goplaylaunch.com/?gameId=SMG_queenOfCairoRoyalMaxways&languageCode=en&host=mobile",
      "isActive": true,
      "sortOrder": 2
    },
    {
      "id": "microgaming-striker-x",
      "title": "Striker X",
      "name": "Striker X",
      "slug": "striker-x",
      "category": "Slots",
      "provider": "MICROGAMING",
      "providerSlug": "microgaming",
      "imageUrl": "https://AIiTGNuAPvSpmLDzUi4pD1vmUiALBQqedVRcnQxjtGA.bithe.net/ImageBuilder/v1/images/en/Square/600x600/P5_strikerX.JPG",
      "thumbnailUrl": "https://AIiTGNuAPvSpmLDzUi4pD1vmUiALBQqedVRcnQxjtGA.bithe.net/ImageBuilder/v1/images/en/Square/600x600/P5_strikerX.JPG",
      "playUrl": "https://anya.microfg.com/game/crash/cr2612/?hide=prov%2CtxID%2Cexit&lang=en&token=eyJhbGciOiJGWEciLCJ0eXAiOiJKV1QifQ.eyJVSUQiOiJkZW1vXzk1MjgiLCJCYWxhbmNlIjo1MDAwMDAwMH0.jdfu_7vyz0HpcnhcsZ4rZriIIkMQq2ajasHEhZSHOkI&ui=6",
      "desktopUrl": "https://anya.microfg.com/game/crash/cr2612/?hide=prov%2CtxID%2Cexit&lang=en&token=eyJhbGciOiJGWEciLCJ0eXAiOiJKV1QifQ.eyJVSUQiOiJkZW1vXzk1MjgiLCJCYWxhbmNlIjo1MDAwMDAwMH0.jdfu_7vyz0HpcnhcsZ4rZriIIkMQq2ajasHEhZSHOkI&ui=6",
      "mobileUrl": "https://anya.microfg.com/game/crash/cr2612/?hide=prov%2CtxID%2Cexit&lang=en&token=eyJhbGciOiJGWEciLCJ0eXAiOiJKV1QifQ.eyJVSUQiOiJkZW1vXzk1MjgiLCJCYWxhbmNlIjo1MDAwMDAwMH0.jdfu_7vyz0HpcnhcsZ4rZriIIkMQq2ajasHEhZSHOkI&ui=6",
      "isActive": true,
      "sortOrder": 3
    },
    {
      "id": "microgaming-bison-fire-charge",
      "title": "Bison Fire Charge",
      "name": "Bison Fire Charge",
      "slug": "bison-fire-charge",
      "category": "Slots",
      "provider": "MICROGAMING",
      "providerSlug": "microgaming",
      "imageUrl": "https://AIiTGNuAPvSpmLDzUi4pD1vmUiALBQqedVRcnQxjtGA.bithe.net/ImageBuilder/v1/images/en/Square/600x600/SMG_bisonFireCharge.JPG",
      "thumbnailUrl": "https://AIiTGNuAPvSpmLDzUi4pD1vmUiALBQqedVRcnQxjtGA.bithe.net/ImageBuilder/v1/images/en/Square/600x600/SMG_bisonFireCharge.JPG",
      "playUrl": "https://aiitgnuapvspmldzui4pd1vmuialbqqedvrcnqxjtga.goplaylaunch.com/?gameId=SMG_bisonFireCharge&languageCode=en&host=desktop",
      "desktopUrl": "https://aiitgnuapvspmldzui4pd1vmuialbqqedvrcnqxjtga.goplaylaunch.com/?gameId=SMG_bisonFireCharge&languageCode=en&host=desktop",
      "mobileUrl": "https://aiitgnuapvspmldzui4pd1vmuialbqqedvrcnqxjtga.goplaylaunch.com/?gameId=SMG_bisonFireCharge&languageCode=en&host=mobile",
      "isActive": true,
      "sortOrder": 4
    },
    {
      "id": "microgaming-playboy-gems-and-desires",
      "title": "Playboy Gems and Desires",
      "name": "Playboy Gems and Desires",
      "slug": "playboy-gems-and-desires",
      "category": "Slots",
      "provider": "MICROGAMING",
      "providerSlug": "microgaming",
      "imageUrl": "https://AIiTGNuAPvSpmLDzUi4pD1vmUiALBQqedVRcnQxjtGA.bithe.net/ImageBuilder/v1/images/en/Square/600x600/SMG_playboyGemsDesires.JPG",
      "thumbnailUrl": "https://AIiTGNuAPvSpmLDzUi4pD1vmUiALBQqedVRcnQxjtGA.bithe.net/ImageBuilder/v1/images/en/Square/600x600/SMG_playboyGemsDesires.JPG",
      "playUrl": "https://aiitgnuapvspmldzui4pd1vmuialbqqedvrcnqxjtga.goplaylaunch.com/?gameId=SMG_playboyGemsDesires&languageCode=en&host=desktop",
      "desktopUrl": "https://aiitgnuapvspmldzui4pd1vmuialbqqedvrcnqxjtga.goplaylaunch.com/?gameId=SMG_playboyGemsDesires&languageCode=en&host=desktop",
      "mobileUrl": "https://aiitgnuapvspmldzui4pd1vmuialbqqedvrcnqxjtga.goplaylaunch.com/?gameId=SMG_playboyGemsDesires&languageCode=en&host=mobile",
      "isActive": true,
      "sortOrder": 5
    },
    {
      "id": "microgaming-soccer-x",
      "title": "Soccer X",
      "name": "Soccer X",
      "slug": "soccer-x",
      "category": "Slots",
      "provider": "MICROGAMING",
      "providerSlug": "microgaming",
      "imageUrl": "https://AIiTGNuAPvSpmLDzUi4pD1vmUiALBQqedVRcnQxjtGA.bithe.net/ImageBuilder/v1/images/en/Square/600x600/SMG_soccerX.JPG",
      "thumbnailUrl": "https://AIiTGNuAPvSpmLDzUi4pD1vmUiALBQqedVRcnQxjtGA.bithe.net/ImageBuilder/v1/images/en/Square/600x600/SMG_soccerX.JPG",
      "playUrl": "https://fooko.suarrest.com/platform/Default.aspx?gameid=soccerXDesktop&languagecode=en&applicationid=163&productId=37241&brand=MGA_demo&username=demo&password=demo&host=desktop",
      "desktopUrl": "https://fooko.suarrest.com/platform/Default.aspx?gameid=soccerXDesktop&languagecode=en&applicationid=163&productId=37241&brand=MGA_demo&username=demo&password=demo&host=desktop",
      "mobileUrl": "https://fooko.suarrest.com/platform/Default.aspx?gameid=soccerXDesktop&languagecode=en&applicationid=163&productId=37241&brand=MGA_demo&username=demo&password=demo&host=mobile",
      "isActive": true,
      "sortOrder": 6
    },
    {
      "id": "microgaming-break-away-candy",
      "title": "Break Away Candy",
      "name": "Break Away Candy",
      "slug": "break-away-candy",
      "category": "Slots",
      "provider": "MICROGAMING",
      "providerSlug": "microgaming",
      "imageUrl": "https://AIiTGNuAPvSpmLDzUi4pD1vmUiALBQqedVRcnQxjtGA.bithe.net/ImageBuilder/v1/images/en/Square/600x600/SMG_breakAwayCandyLinkMerge.JPG",
      "thumbnailUrl": "https://AIiTGNuAPvSpmLDzUi4pD1vmUiALBQqedVRcnQxjtGA.bithe.net/ImageBuilder/v1/images/en/Square/600x600/SMG_breakAwayCandyLinkMerge.JPG",
      "playUrl": "https://aiitgnuapvspmldzui4pd1vmuialbqqedvrcnqxjtga.goplaylaunch.com/?gameId=SMG_breakAwayCandyLinkMerge&languageCode=en&host=desktop",
      "desktopUrl": "https://aiitgnuapvspmldzui4pd1vmuialbqqedvrcnqxjtga.goplaylaunch.com/?gameId=SMG_breakAwayCandyLinkMerge&languageCode=en&host=desktop",
      "mobileUrl": "https://aiitgnuapvspmldzui4pd1vmuialbqqedvrcnqxjtga.goplaylaunch.com/?gameId=SMG_breakAwayCandyLinkMerge&languageCode=en&host=mobile",
      "isActive": true,
      "sortOrder": 7
    },
    {
      "id": "microgaming-ultimate-goal-blitz",
      "title": "Ultimate Goal Blitz",
      "name": "Ultimate Goal Blitz",
      "slug": "ultimate-goal-blitz",
      "category": "Slots",
      "provider": "MICROGAMING",
      "providerSlug": "microgaming",
      "imageUrl": "https://AIiTGNuAPvSpmLDzUi4pD1vmUiALBQqedVRcnQxjtGA.bithe.net/ImageBuilder/v1/images/en/Square/600x600/SMG_ultimateGoalBlitz.JPG",
      "thumbnailUrl": "https://AIiTGNuAPvSpmLDzUi4pD1vmUiALBQqedVRcnQxjtGA.bithe.net/ImageBuilder/v1/images/en/Square/600x600/SMG_ultimateGoalBlitz.JPG",
      "playUrl": "https://aiitgnuapvspmldzui4pd1vmuialbqqedvrcnqxjtga.goplaylaunch.com/?gameId=SMG_ultimateGoalBlitz&languageCode=en&host=desktop",
      "desktopUrl": "https://aiitgnuapvspmldzui4pd1vmuialbqqedvrcnqxjtga.goplaylaunch.com/?gameId=SMG_ultimateGoalBlitz&languageCode=en&host=desktop",
      "mobileUrl": "https://aiitgnuapvspmldzui4pd1vmuialbqqedvrcnqxjtga.goplaylaunch.com/?gameId=SMG_ultimateGoalBlitz&languageCode=en&host=mobile",
      "isActive": true,
      "sortOrder": 8
    },
    {
      "id": "microgaming-wrath-of-seth-split",
      "title": "Wrath of Seth – Split",
      "name": "Wrath of Seth – Split",
      "slug": "wrath-of-seth-split",
      "category": "Slots",
      "provider": "MICROGAMING",
      "providerSlug": "microgaming",
      "imageUrl": "https://AIiTGNuAPvSpmLDzUi4pD1vmUiALBQqedVRcnQxjtGA.bithe.net/ImageBuilder/v1/images/en/Square/600x600/smg_wrathofSethSplit.JPG",
      "thumbnailUrl": "https://AIiTGNuAPvSpmLDzUi4pD1vmUiALBQqedVRcnQxjtGA.bithe.net/ImageBuilder/v1/images/en/Square/600x600/smg_wrathofSethSplit.JPG",
      "playUrl": "https://sfggame.qfconnect.net/as-lobby/demoSession/launch?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJnYW1lSWQiOiIxMzIwIiwibGFuZ0NvZGUiOiJlbiIsImF1ZCI6Ii9kZW1vU2Vzc2lvbi9sYXVuY2giLCJleHAiOjE3ODA4NDE2NzUsImlhdCI6MTc4MDgzODA3NSwibmJmIjoxNzgwODM4MDc1fQ.D6PoVxqh2912ElbNEZaAwlm7xEzkDCRJlHXMIKpXI3c",
      "desktopUrl": "https://sfggame.qfconnect.net/as-lobby/demoSession/launch?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJnYW1lSWQiOiIxMzIwIiwibGFuZ0NvZGUiOiJlbiIsImF1ZCI6Ii9kZW1vU2Vzc2lvbi9sYXVuY2giLCJleHAiOjE3ODA4NDE2NzUsImlhdCI6MTc4MDgzODA3NSwibmJmIjoxNzgwODM4MDc1fQ.D6PoVxqh2912ElbNEZaAwlm7xEzkDCRJlHXMIKpXI3c",
      "mobileUrl": "https://sfggame.qfconnect.net/as-lobby/demoSession/launch?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJnYW1lSWQiOiIxMzIwIiwibGFuZ0NvZGUiOiJlbiIsImF1ZCI6Ii9kZW1vU2Vzc2lvbi9sYXVuY2giLCJleHAiOjE3ODA4NDE2NzUsImlhdCI6MTc4MDgzODA3NSwibmJmIjoxNzgwODM4MDc1fQ.D6PoVxqh2912ElbNEZaAwlm7xEzkDCRJlHXMIKpXI3c",
      "isActive": true,
      "sortOrder": 9
    },
    {
      "id": "microgaming-123-soccer",
      "title": "123 Soccer",
      "name": "123 Soccer",
      "slug": "123-soccer",
      "category": "Slots",
      "provider": "MICROGAMING",
      "providerSlug": "microgaming",
      "imageUrl": "https://AIiTGNuAPvSpmLDzUi4pD1vmUiALBQqedVRcnQxjtGA.bithe.net/ImageBuilder/v1/images/en/Square/600x600/SMG_123SoccerLinkMerge.JPG",
      "thumbnailUrl": "https://AIiTGNuAPvSpmLDzUi4pD1vmUiALBQqedVRcnQxjtGA.bithe.net/ImageBuilder/v1/images/en/Square/600x600/SMG_123SoccerLinkMerge.JPG",
      "playUrl": "https://aiitgnuapvspmldzui4pd1vmuialbqqedvrcnqxjtga.goplaylaunch.com/?gameId=SMG_123SoccerLinkMerge&languageCode=en&host=desktop",
      "desktopUrl": "https://aiitgnuapvspmldzui4pd1vmuialbqqedvrcnqxjtga.goplaylaunch.com/?gameId=SMG_123SoccerLinkMerge&languageCode=en&host=desktop",
      "mobileUrl": "https://aiitgnuapvspmldzui4pd1vmuialbqqedvrcnqxjtga.goplaylaunch.com/?gameId=SMG_123SoccerLinkMerge&languageCode=en&host=mobile",
      "isActive": true,
      "sortOrder": 10
    },
    {
      "id": "microgaming-almighty-zeus-wilds",
      "title": "Almighty Zeus Wilds",
      "name": "Almighty Zeus Wilds",
      "slug": "almighty-zeus-wilds",
      "category": "Slots",
      "provider": "MICROGAMING",
      "providerSlug": "microgaming",
      "imageUrl": "https://AIiTGNuAPvSpmLDzUi4pD1vmUiALBQqedVRcnQxjtGA.bithe.net/ImageBuilder/v1/images/en/Square/600x600/SMG_almightyZeusWildsLinkMerge.JPG",
      "thumbnailUrl": "https://AIiTGNuAPvSpmLDzUi4pD1vmUiALBQqedVRcnQxjtGA.bithe.net/ImageBuilder/v1/images/en/Square/600x600/SMG_almightyZeusWildsLinkMerge.JPG",
      "playUrl": "https://aiitgnuapvspmldzui4pd1vmuialbqqedvrcnqxjtga.goplaylaunch.com/?gameId=SMG_almightyZeusWildsLinkMerge&languageCode=en&host=desktop",
      "desktopUrl": "https://aiitgnuapvspmldzui4pd1vmuialbqqedvrcnqxjtga.goplaylaunch.com/?gameId=SMG_almightyZeusWildsLinkMerge&languageCode=en&host=desktop",
      "mobileUrl": "https://aiitgnuapvspmldzui4pd1vmuialbqqedvrcnqxjtga.goplaylaunch.com/?gameId=SMG_almightyZeusWildsLinkMerge&languageCode=en&host=mobile",
      "isActive": true,
      "sortOrder": 11
    },
    {
      "id": "microgaming-lucky-twins-wild",
      "title": "Lucky Twins Wild",
      "name": "Lucky Twins Wild",
      "slug": "lucky-twins-wild",
      "category": "Slots",
      "provider": "MICROGAMING",
      "providerSlug": "microgaming",
      "imageUrl": "https://AIiTGNuAPvSpmLDzUi4pD1vmUiALBQqedVRcnQxjtGA.bithe.net/ImageBuilder/v1/images/en/Square/600x600/SMG_luckyTwinsWildsLinkMerge.JPG",
      "thumbnailUrl": "https://AIiTGNuAPvSpmLDzUi4pD1vmUiALBQqedVRcnQxjtGA.bithe.net/ImageBuilder/v1/images/en/Square/600x600/SMG_luckyTwinsWildsLinkMerge.JPG",
      "playUrl": "https://aiitgnuapvspmldzui4pd1vmuialbqqedvrcnqxjtga.goplaylaunch.com/?gameId=SMG_luckyTwinsWildsLinkMerge&languageCode=en&host=desktop",
      "desktopUrl": "https://aiitgnuapvspmldzui4pd1vmuialbqqedvrcnqxjtga.goplaylaunch.com/?gameId=SMG_luckyTwinsWildsLinkMerge&languageCode=en&host=desktop",
      "mobileUrl": "https://aiitgnuapvspmldzui4pd1vmuialbqqedvrcnqxjtga.goplaylaunch.com/?gameId=SMG_luckyTwinsWildsLinkMerge&languageCode=en&host=mobile",
      "isActive": true,
      "sortOrder": 12
    }
  ]
} satisfies Record<string, PublicProviderGame[]>;

export function getPublicProviderCards() {
  return publicGameProviders
    .filter((provider) => provider.isActive)
    .sort((a, b) => a.sortOrder - b.sortOrder);
}

export function getPublicProviderGameList(providerSlug: string) {
  return (publicProviderGames[providerSlug] || [])
    .filter((game) => game.isActive)
    .sort((a, b) => a.sortOrder - b.sortOrder);
}

export function getAllPublicGames() {
  return Object.values(publicProviderGames)
    .flat()
    .filter((game) => game.isActive)
    .sort((a, b) => {
      if (a.providerSlug !== b.providerSlug) {
        const providerA = publicGameProviders.find((provider) => provider.slug === a.providerSlug)?.sortOrder ?? 999;
        const providerB = publicGameProviders.find((provider) => provider.slug === b.providerSlug)?.sortOrder ?? 999;

        return providerA - providerB;
      }

      return a.sortOrder - b.sortOrder;
    });
}
